version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    labels:
      - "dependencies"
      - "maven"
    commit-message:
      prefix: "[Maven]"
    target-branch: "develop"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "[github-actions]"
    target-branch: "develop"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "[docker]"
    target-branch: "develop"
    schedule:
      interval: "weekly"
