sonar.projectKey=karate-management-platform
sonar.projectName=Karate Management Platform
sonar.projectVersion=1.0

sonar.sources=src/main/java
sonar.java.binaries=target/classes
sonar.java.source=17

sonar.host.url=http://localhost:9000
sonar.token=sqp_9f5ff657ac6e3bf299818c6b33b2b1eed6fa92a4

#mvn clean verify sonar:sonar -DskipTests -Dsonar.projectKey=karate-management-platform   -Dsonar.projectName='Karate Management Platform'   -Dsonar.host.url=http://localhost:9000   -Dsonar.token=sqp_9f5ff657ac6e3bf299818c6b33b2b1eed6fa92a4
