spring.application.name=karate-auth-service

# Server Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/karate_users_db
spring.datasource.username=karate_user
spring.datasource.password=Karate.user2025
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Swagger Configuration
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true