spring.application.name=karate-auth-service
spring.datasource.url=jdbc:postgresql://localhost:5432/karate_app_db
spring.datasource.username=karate_user
spring.datasource.password=Karate.user2025
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
