package ro.unibuc.fmi.karate_management_platform.repositories.request;

import ro.unibuc.fmi.karate_management_platform.models.request.competition.CompetitionCreationRequest;

public interface CompetitionCreationRequestRepository extends RequestWithRolesApprovalRepository<CompetitionCreationRequest> {
}