CREATE SEQUENCE IF NOT EXISTS clubs_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS invitations_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS request_info_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS users_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE athlete_coach
(
    athlete_id BIGINT NOT NULL,
    coach_id   BIGINT NOT NULL,
    CONSTRAINT athlete_coach_pkey PRIMARY KEY (athlete_id, coach_id)
);

CREATE TABLE athlete_creation_requests
(
    club_id BIGINT,
    height  INTEGER,
    weight  INTEGER,
    id      BIGINT NOT NULL,
    CONSTRAINT athlete_creation_requests_pkey PRIMARY KEY (id)
);

CREATE TABLE athlete_creation_requests_approver_users
(
    request_id BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    CONSTRAINT athlete_creation_requests_approver_users_pkey PRIMARY KEY (request_id, user_id)
);

CREATE TABLE athletes
(
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    height     INTEGER                     NOT NULL,
    weight     INTEGER                     NOT NULL,
    user_id    BIGINT                      NOT NULL,
    CONSTRAINT athletes_pkey PRIMARY KEY (user_id)
);

CREATE TABLE clubs
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    acronym    VARCHAR(255)                            NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    CONSTRAINT clubs_pkey PRIMARY KEY (id)
);

CREATE TABLE coach_creation_request_approver_roles
(
    coach_creation_request_id BIGINT       NOT NULL,
    approver_roles            VARCHAR(255) NOT NULL,
    CONSTRAINT coach_creation_request_approver_roles_pkey PRIMARY KEY (coach_creation_request_id, approver_roles)
);

CREATE TABLE coach_creation_requests
(
    license_series VARCHAR(255) NOT NULL,
    license_number VARCHAR(255) NOT NULL,
    id             BIGINT       NOT NULL,
    CONSTRAINT coach_creation_requests_pkey PRIMARY KEY (id)
);

CREATE TABLE coaches
(
    created_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    license_series VARCHAR(255)                NOT NULL,
    license_number VARCHAR(255)                NOT NULL,
    user_id        BIGINT                      NOT NULL,
    club_id        BIGINT,
    CONSTRAINT coaches_pkey PRIMARY KEY (user_id)
);

CREATE TABLE invitations
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by BIGINT                                  NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    token      VARCHAR(255)                            NOT NULL,
    type       VARCHAR(255)                            NOT NULL,
    CONSTRAINT invitations_pkey PRIMARY KEY (id)
);

CREATE TABLE organizer_creation_request_approver_roles
(
    organizer_creation_request_id BIGINT       NOT NULL,
    approver_roles                VARCHAR(255) NOT NULL,
    CONSTRAINT organizer_creation_request_approver_roles_pkey PRIMARY KEY (organizer_creation_request_id, approver_roles)
);

CREATE TABLE organizer_creation_requests
(
    trn_series VARCHAR(255) NOT NULL,
    id         BIGINT       NOT NULL,
    CONSTRAINT organizer_creation_requests_pkey PRIMARY KEY (id)
);

CREATE TABLE organizers
(
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    trn_series VARCHAR(255)                NOT NULL,
    user_id    BIGINT                      NOT NULL,
    CONSTRAINT organizers_pkey PRIMARY KEY (user_id)
);

CREATE TABLE referee_creation_request_approver_roles
(
    referee_creation_request_id BIGINT       NOT NULL,
    approver_roles              VARCHAR(255) NOT NULL,
    CONSTRAINT referee_creation_request_approver_roles_pkey PRIMARY KEY (referee_creation_request_id, approver_roles)
);

CREATE TABLE referee_creation_requests
(
    license_series VARCHAR(255) NOT NULL,
    license_number VARCHAR(255) NOT NULL,
    category       VARCHAR(255),
    id             BIGINT       NOT NULL,
    CONSTRAINT referee_creation_requests_pkey PRIMARY KEY (id)
);

CREATE TABLE referees
(
    created_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    category       VARCHAR(255)                NOT NULL,
    license_series VARCHAR(255)                NOT NULL,
    license_number VARCHAR(255)                NOT NULL,
    user_id        BIGINT                      NOT NULL,
    CONSTRAINT referees_pkey PRIMARY KEY (user_id)
);

CREATE TABLE request_info
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_updated_by_id BIGINT                                  NOT NULL,
    request_scope      VARCHAR(255)                            NOT NULL,
    request_status     VARCHAR(255)                            NOT NULL,
    request_type       VARCHAR(255)                            NOT NULL,
    created_by_id      BIGINT                                  NOT NULL,
    CONSTRAINT request_info_pkey PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    user_id BIGINT NOT NULL,
    role    VARCHAR(255)
);

CREATE TABLE users
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    birth_date          date,
    email               VARCHAR(255)                            NOT NULL,
    first_name          VARCHAR(120),
    gender              VARCHAR(255),
    last_name           VARCHAR(60),
    nationality         VARCHAR(100),
    password            VARCHAR(255)                            NOT NULL,
    profile_picture_url VARCHAR(255),
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

ALTER TABLE clubs
    ADD CONSTRAINT uk7x7wph0bo1s930dmfh32t3soh UNIQUE (name);

ALTER TABLE clubs
    ADD CONSTRAINT ukmn46hw5ge1dhhb325fddyjeog UNIQUE (acronym);

ALTER TABLE invitations
    ADD CONSTRAINT ukt4i6esv44p6yi7cxq277vlo3i UNIQUE (token);

ALTER TABLE organizer_creation_request_approver_roles
    ADD CONSTRAINT fk17jnpo79s8etfa94313o2xst7 FOREIGN KEY (organizer_creation_request_id) REFERENCES organizer_creation_requests (id) ON DELETE NO ACTION;

ALTER TABLE coaches
    ADD CONSTRAINT fk287eoy53kddnjjtestb8xyu16 FOREIGN KEY (club_id) REFERENCES clubs (id) ON DELETE NO ACTION;

ALTER TABLE coach_creation_request_approver_roles
    ADD CONSTRAINT fk3gx8al4l5glftsd437cmwhab8 FOREIGN KEY (coach_creation_request_id) REFERENCES coach_creation_requests (id) ON DELETE NO ACTION;

ALTER TABLE coach_creation_requests
    ADD CONSTRAINT fk3j5tj0t5hxlhk7rislwd004et FOREIGN KEY (id) REFERENCES request_info (id) ON DELETE NO ACTION;

ALTER TABLE organizer_creation_requests
    ADD CONSTRAINT fk3qq95pnbomhv6uqb9qimjorxc FOREIGN KEY (id) REFERENCES request_info (id) ON DELETE NO ACTION;

ALTER TABLE referees
    ADD CONSTRAINT fk5qot1lapdj7h15jhdeyiodf12 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE organizers
    ADD CONSTRAINT fk7kpidig5uothy6p9ttywnif6l FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE request_info
    ADD CONSTRAINT fkac69tc5und90slfe8hrf4sbnq FOREIGN KEY (created_by_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE referee_creation_requests
    ADD CONSTRAINT fkbj7b72det0m5a0vwd6hm34ny3 FOREIGN KEY (id) REFERENCES request_info (id) ON DELETE NO ACTION;

ALTER TABLE athlete_creation_requests_approver_users
    ADD CONSTRAINT fkbo1n3ixdb281bryeb99himcvl FOREIGN KEY (request_id) REFERENCES athlete_creation_requests (id) ON DELETE NO ACTION;

ALTER TABLE athlete_creation_requests_approver_users
    ADD CONSTRAINT fkcetes35kumay3sd3o820j6j15 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE referee_creation_request_approver_roles
    ADD CONSTRAINT fkcl5uwuafxa5h8s2s0gled47hb FOREIGN KEY (referee_creation_request_id) REFERENCES referee_creation_requests (id) ON DELETE NO ACTION;

ALTER TABLE athlete_coach
    ADD CONSTRAINT fkclkbh7ru1n698ictf4pa7sptc FOREIGN KEY (coach_id) REFERENCES coaches (user_id) ON DELETE NO ACTION;

ALTER TABLE athletes
    ADD CONSTRAINT fke96lkn1snw5m60m0wf4vmheqv FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE athlete_creation_requests
    ADD CONSTRAINT fkhj44qrpbvpfpc80fna5m6va6m FOREIGN KEY (id) REFERENCES request_info (id) ON DELETE NO ACTION;

ALTER TABLE coaches
    ADD CONSTRAINT fko2s6iuqyundkjflwh6ps8d0f0 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE athlete_coach
    ADD CONSTRAINT fks0lcama8w22na2t5efw1dd0bd FOREIGN KEY (athlete_id) REFERENCES athletes (user_id) ON DELETE NO ACTION;