CREATE TABLE athlete_competition_category
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    athlete_id     BIGINT                                  NOT NULL,
    competition_id BIGINT                                  NOT NULL,
    category_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_athlete_competition_category PRIMARY KEY (id)
);

ALTER TABLE kata_category
    ADD kata_belt_range VARCHAR(255);

ALTER TABLE kata_category
    ALTER COLUMN kata_belt_range SET NOT NULL;

ALTER TABLE kumite_category
    ADD kumite_division_range VARCHAR(255) NOT NULL;

ALTER TABLE kumite_category
    ALTER COLUMN kumite_division_range SET NOT NULL;

ALTER TABLE athlete_competition_category
    ADD CONSTRAINT FK_ATHLETE_COMPETITION_CATEGORY_ON_ATHLETE FOREIGN KEY (athlete_id) REFERENCES athletes (user_id);

ALTER TABLE athlete_competition_category
    ADD CONSTRAINT FK_ATHLETE_COMPETITION_CATEGORY_ON_COMPETITION FOREIGN KEY (competition_id) REFERENCES competitions (id);

ALTER TABLE kata_category
    DROP COLUMN kata_category_type;

ALTER TABLE kumite_category
    DROP COLUMN weight_max;

ALTER TABLE kumite_category
    DROP COLUMN weight_min;

ALTER TABLE athletes
    DROP COLUMN height;

ALTER TABLE athletes
    DROP COLUMN weight;

ALTER TABLE athletes
    ADD height SMALLINT NOT NULL;

ALTER TABLE athletes
    ADD weight SMALLINT NOT NULL;