DROP TABLE IF EXISTS individual_category_athletes;
DROP TABLE IF EXISTS individual_kata_athletes;

CREATE TABLE individual_category_participation
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_id     BIGINT,
    competition_id  BIGINT,
    athlete_user_id BIGINT,
    CONSTRAINT pk_individual_category_participation PRIMARY KEY (id)
);

ALTER TABLE individual_category_participation
    ADD CONSTRAINT FK_INDIVIDUAL_CATEGORY_PARTICIPATION_ON_ATHLETE_USER FOREIGN KEY (athlete_user_id) REFERENCES athletes (user_id);

ALTER TABLE individual_category_participation
    ADD CONSTRAINT FK_INDIVIDUAL_CATEGORY_PARTICIPATION_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES individual_category (id);

ALTER TABLE individual_category_participation
    ADD CONSTRAINT FK_INDIVIDUAL_CATEGORY_PARTICIPATION_ON_COMPETITION FOREIGN KEY (competition_id) REFERENCES competitions (id);