DROP TABLE IF EXISTS team_category_teams;

CREATE TABLE team_category_participation
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_id    BIGINT,
    competition_id BIGINT,
    team_id        BIGINT,
    CONSTRAINT pk_team_category_participation PRIMARY KEY (id)
);

ALTER TABLE team_category_participation
    ADD CONSTRAINT FK_TEAM_CATEGORY_PARTICIPATION_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES team_category (id);

ALTER TABLE team_category_participation
    ADD CONSTRAINT FK_TEAM_CATEGORY_PARTICIPATION_ON_COMPETITION FOREIGN KEY (competition_id) REFERENCES competitions (id);

ALTER TABLE team_category_participation
    ADD CONSTRAINT FK_TEAM_CATEGORY_PARTICIPATION_ON_TEAM FOREIGN KEY (team_id) REFERENCES teams (id);
