-- Drop existing constraints
ALTER TABLE individual_category_participation
    DROP CONSTRAINT IF EXISTS fk_individual_category_participation_on_category;

ALTER TABLE individual_category_participation
    DROP CONSTRAINT IF EXISTS fk_individual_category_participation_on_competition;

ALTER TABLE team_category_participation
    DROP CONSTRAINT IF EXISTS fk_team_category_participation_on_category;

ALTER TABLE team_category_participation
    DROP CONSTRAINT IF EXISTS fk_team_category_participation_on_competition;

-- Create the base category_participation table
CREATE TABLE category_participation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    competition_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    duration_minutes INTEGER NOT NULL,
    CONSTRAINT pk_category_participation PRIMARY KEY (id)
);

-- Add foreign key constraints to category_participation
ALTER TABLE category_participation
    ADD CONSTRAINT FK_CATEGORY_PARTICIPATION_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id);

ALTER TABLE category_participation
    ADD CONSTRAINT FK_CATEGORY_PARTICIPATION_ON_COMPETITION FOREIGN KEY (competition_id) REFERENCES competitions (id);

-- Migrate data from individual_category_participation
INSERT INTO category_participation (id, competition_id, duration_minutes, category_id)
SELECT id, competition_id, duration_minutes, category_id
FROM individual_category_participation
ON CONFLICT (id) DO NOTHING;

-- Migrate data from team_category_participation
INSERT INTO category_participation (id, competition_id, duration_minutes, category_id)
SELECT id, competition_id, duration_minutes, category_id
FROM team_category_participation
ON CONFLICT (id) DO NOTHING;

-- Modify individual_category_participation
ALTER TABLE individual_category_participation
    DROP COLUMN competition_id,
    DROP COLUMN duration_minutes,
    DROP COLUMN category_id,
    ADD CONSTRAINT FK_INDIVIDUAL_CATEGORY_PARTICIPATION_ON_ID FOREIGN KEY (id) REFERENCES category_participation (id);

-- Modify team_category_participation
ALTER TABLE team_category_participation
    DROP COLUMN competition_id,
    DROP COLUMN duration_minutes,
    DROP COLUMN category_id,
    ADD CONSTRAINT FK_TEAM_CATEGORY_PARTICIPATION_ON_ID FOREIGN KEY (id) REFERENCES category_participation (id);

-- Add indexes for better performance
CREATE INDEX idx_category_participation_category_id ON category_participation(category_id);
CREATE INDEX idx_category_participation_competition_id ON category_participation(competition_id); 