ALTER TABLE athletes ADD COLUMN points INTEGER NOT NULL DEFAULT 0;
ALTER TABLE athletes ADD COLUMN gold_medals INTEGER NOT NULL DEFAULT 0;
ALTER TABLE athletes ADD COLUMN silver_medals INTEGER NOT NULL DEFAULT 0;
ALTER TABLE athletes ADD COLUMN bronze_medals INTEGER NOT NULL DEFAULT 0; 