ALTER TABLE organizer_creation_request_approver_roles
DROP
CONSTRAINT fk17jnpo79s8etfa94313o2xst7;

ALTER TABLE referee_creation_request_approver_roles
DROP
CONSTRAINT fkcl5uwuafxa5h8s2s0gled47hb;

CREATE TABLE categories
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    discipline_type    VARCHAR(31),
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    age_group          VARCHAR(255)                            NOT NULL,
    gender             VARCHAR(255)                            NOT NULL,
    is_default         BOOLEAN                                 NOT NULL,
    weight_min         INTEGER                                 NOT NULL,
    weight_max         INTEGER                                 NOT NULL,
    kata_category_type VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE competition_categories
(
    category_id    BIGINT NOT NULL,
    competition_id BIGINT NOT NULL
);

CREATE TABLE competitions
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    location     VARCHAR(255)                            NOT NULL,
    date         date                                    NOT NULL,
    organizer_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_competitions PRIMARY KEY (id)
);

CREATE TABLE individual_kata_athletes
(
    athlete_id  BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    CONSTRAINT pk_individual_kata_athletes PRIMARY KEY (athlete_id, category_id)
);

CREATE TABLE individual_kata_matches
(
    id BIGINT NOT NULL,
    CONSTRAINT pk_individual_kata_matches PRIMARY KEY (id)
);

CREATE TABLE individual_kumite_matches
(
    id               BIGINT NOT NULL,
    athlete_left_id  BIGINT NOT NULL,
    athlete_right_id BIGINT NOT NULL,
    CONSTRAINT pk_individual_kumite_matches PRIMARY KEY (id)
);

CREATE TABLE matches
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    scheduled_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    category_id    BIGINT                                  NOT NULL,
    result         VARCHAR(255),
    CONSTRAINT pk_matches PRIMARY KEY (id)
);

CREATE TABLE team_athletes
(
    athlete_id BIGINT NOT NULL,
    team_id    BIGINT NOT NULL,
    CONSTRAINT pk_team_athletes PRIMARY KEY (athlete_id, team_id)
);

CREATE TABLE team_kata_matches
(
    id BIGINT NOT NULL,
    CONSTRAINT pk_team_kata_matches PRIMARY KEY (id)
);

CREATE TABLE team_kata_matches_teams
(
    team_id            BIGINT NOT NULL,
    team_kata_match_id BIGINT NOT NULL
);

CREATE TABLE team_kumite_matches
(
    id            BIGINT NOT NULL,
    team_left_id  BIGINT NOT NULL,
    team_right_id BIGINT NOT NULL,
    CONSTRAINT pk_team_kumite_matches PRIMARY KEY (id)
);

CREATE TABLE teams
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    team_name  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_teams PRIMARY KEY (id)
);

ALTER TABLE referees
    ADD referee_level VARCHAR(255);

ALTER TABLE referees
    ALTER COLUMN referee_level SET NOT NULL;

ALTER TABLE competitions
    ADD CONSTRAINT FK_COMPETITIONS_ON_ORGANIZER FOREIGN KEY (organizer_id) REFERENCES organizers (user_id);

ALTER TABLE individual_kata_matches
    ADD CONSTRAINT FK_INDIVIDUAL_KATA_MATCHES_ON_ID FOREIGN KEY (id) REFERENCES matches (id);

ALTER TABLE individual_kumite_matches
    ADD CONSTRAINT FK_INDIVIDUAL_KUMITE_MATCHES_ON_ATHLETE_LEFT FOREIGN KEY (athlete_left_id) REFERENCES athletes (user_id);

ALTER TABLE individual_kumite_matches
    ADD CONSTRAINT FK_INDIVIDUAL_KUMITE_MATCHES_ON_ATHLETE_RIGHT FOREIGN KEY (athlete_right_id) REFERENCES athletes (user_id);

ALTER TABLE individual_kumite_matches
    ADD CONSTRAINT FK_INDIVIDUAL_KUMITE_MATCHES_ON_ID FOREIGN KEY (id) REFERENCES matches (id);

ALTER TABLE matches
    ADD CONSTRAINT FK_MATCHES_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE team_kata_matches
    ADD CONSTRAINT FK_TEAM_KATA_MATCHES_ON_ID FOREIGN KEY (id) REFERENCES matches (id);

ALTER TABLE team_kumite_matches
    ADD CONSTRAINT FK_TEAM_KUMITE_MATCHES_ON_ID FOREIGN KEY (id) REFERENCES matches (id);

ALTER TABLE team_kumite_matches
    ADD CONSTRAINT FK_TEAM_KUMITE_MATCHES_ON_TEAM_LEFT FOREIGN KEY (team_left_id) REFERENCES teams (id);

ALTER TABLE team_kumite_matches
    ADD CONSTRAINT FK_TEAM_KUMITE_MATCHES_ON_TEAM_RIGHT FOREIGN KEY (team_right_id) REFERENCES teams (id);

ALTER TABLE competition_categories
    ADD CONSTRAINT fk_comcat_on_category FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE competition_categories
    ADD CONSTRAINT fk_comcat_on_competition FOREIGN KEY (competition_id) REFERENCES competitions (id);

ALTER TABLE individual_kata_athletes
    ADD CONSTRAINT fk_indkatath_on_athlete FOREIGN KEY (athlete_id) REFERENCES athletes (user_id);

ALTER TABLE individual_kata_athletes
    ADD CONSTRAINT fk_indkatath_on_individual_kata_match FOREIGN KEY (category_id) REFERENCES individual_kata_matches (id);

ALTER TABLE team_athletes
    ADD CONSTRAINT fk_teaath_on_athlete FOREIGN KEY (athlete_id) REFERENCES athletes (user_id);

ALTER TABLE team_athletes
    ADD CONSTRAINT fk_teaath_on_team FOREIGN KEY (team_id) REFERENCES teams (id);

ALTER TABLE team_kata_matches_teams
    ADD CONSTRAINT fk_teakatmattea_on_team FOREIGN KEY (team_id) REFERENCES teams (id);

ALTER TABLE team_kata_matches_teams
    ADD CONSTRAINT fk_teakatmattea_on_team_kata_match FOREIGN KEY (team_kata_match_id) REFERENCES team_kata_matches (id);

DROP TABLE organizer_creation_request_approver_roles CASCADE;

DROP TABLE referee_creation_request_approver_roles CASCADE;

ALTER TABLE coach_creation_request_approver_roles
DROP
CONSTRAINT coach_creation_request_approver_roles_pkey;

ALTER TABLE referee_creation_requests
DROP
COLUMN category;

ALTER TABLE referee_creation_requests
DROP
COLUMN license_number;

ALTER TABLE referee_creation_requests
DROP
COLUMN license_series;

ALTER TABLE referees
DROP
COLUMN category;

ALTER TABLE athlete_creation_requests
DROP
COLUMN club_id;

ALTER TABLE athlete_creation_requests
DROP
COLUMN height;

ALTER TABLE athlete_creation_requests
DROP
COLUMN weight;

ALTER TABLE coach_creation_requests
DROP
COLUMN license_number;

ALTER TABLE coach_creation_requests
DROP
COLUMN license_series;

ALTER TABLE organizer_creation_requests
DROP
COLUMN trn_series;

DROP SEQUENCE clubs_id_seq CASCADE;

DROP SEQUENCE invitations_id_seq CASCADE;

DROP SEQUENCE request_info_id_seq CASCADE;

DROP SEQUENCE users_id_seq CASCADE;

ALTER TABLE coaches
ALTER
COLUMN license_number TYPE VARCHAR USING (license_number::VARCHAR);

ALTER TABLE referees
ALTER
COLUMN license_number TYPE VARCHAR USING (license_number::VARCHAR);

ALTER TABLE coaches
ALTER
COLUMN license_series TYPE VARCHAR USING (license_series::VARCHAR);

ALTER TABLE referees
ALTER
COLUMN license_series TYPE VARCHAR USING (license_series::VARCHAR);

ALTER TABLE organizers
ALTER
COLUMN trn_series TYPE VARCHAR USING (trn_series::VARCHAR);