ALTER TABLE organizer_creation_request_approver_roles
DROP
CONSTRAINT fk17jnpo79s8etfa94313o2xst7;

ALTER TABLE referee_creation_request_approver_roles
DROP
CONSTRAINT fkcl5uwuafxa5h8s2s0gled47hb;

CREATE TABLE categories
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    age_group      VARCHAR(255)                            NOT NULL,
    weight_min     INTEGER                                 NOT NULL,
    weight_max     INTEGER                                 NOT NULL,
    gender         VARCHAR(255)                            NOT NULL,
    is_default     BOOLEAN                                 NOT NULL,
    competition_id BIGINT,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE competitions
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    location     VARCHAR(255)                            NOT NULL,
    date         date                                    NOT NULL,
    organizer_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_competitions PRIMARY KEY (id)
);

CREATE TABLE match_referees
(
    match_id   BIGINT NOT NULL,
    referee_id BIGINT NOT NULL,
    CONSTRAINT pk_match_referees PRIMARY KEY (match_id, referee_id)
);

CREATE TABLE matches
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    match_type       VARCHAR(31),
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    scheduled_time   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    competition_id   BIGINT                                  NOT NULL,
    category_id      BIGINT                                  NOT NULL,
    result           VARCHAR(255),
    athlete_left_id  BIGINT                                  NOT NULL,
    athlete_right_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_matches PRIMARY KEY (id)
);

CREATE TABLE team_left_athletes
(
    athlete_id BIGINT NOT NULL,
    match_id   BIGINT NOT NULL,
    CONSTRAINT pk_team_left_athletes PRIMARY KEY (athlete_id, match_id)
);

CREATE TABLE team_right_athletes
(
    athlete_id BIGINT NOT NULL,
    match_id   BIGINT NOT NULL,
    CONSTRAINT pk_team_right_athletes PRIMARY KEY (athlete_id, match_id)
);

ALTER TABLE referees
    ADD referee_level VARCHAR(255);

ALTER TABLE referees
    ALTER COLUMN referee_level SET NOT NULL;

ALTER TABLE categories
    ADD CONSTRAINT FK_CATEGORIES_ON_COMPETITION FOREIGN KEY (competition_id) REFERENCES competitions (id);

ALTER TABLE competitions
    ADD CONSTRAINT FK_COMPETITIONS_ON_ORGANIZER FOREIGN KEY (organizer_id) REFERENCES organizers (user_id);

ALTER TABLE matches
    ADD CONSTRAINT FK_MATCHES_ON_ATHLETE_LEFT FOREIGN KEY (athlete_left_id) REFERENCES athletes (user_id);

ALTER TABLE matches
    ADD CONSTRAINT FK_MATCHES_ON_ATHLETE_RIGHT FOREIGN KEY (athlete_right_id) REFERENCES athletes (user_id);

ALTER TABLE matches
    ADD CONSTRAINT FK_MATCHES_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE matches
    ADD CONSTRAINT FK_MATCHES_ON_COMPETITION FOREIGN KEY (competition_id) REFERENCES competitions (id);

ALTER TABLE match_referees
    ADD CONSTRAINT fk_matref_on_match FOREIGN KEY (match_id) REFERENCES matches (id);

ALTER TABLE match_referees
    ADD CONSTRAINT fk_matref_on_referee FOREIGN KEY (referee_id) REFERENCES referees (user_id);

ALTER TABLE team_left_athletes
    ADD CONSTRAINT fk_tealefath_on_athlete FOREIGN KEY (athlete_id) REFERENCES athletes (user_id);

ALTER TABLE team_left_athletes
    ADD CONSTRAINT fk_tealefath_on_team_match FOREIGN KEY (match_id) REFERENCES matches (id);

ALTER TABLE team_right_athletes
    ADD CONSTRAINT fk_tearigath_on_athlete FOREIGN KEY (athlete_id) REFERENCES athletes (user_id);

ALTER TABLE team_right_athletes
    ADD CONSTRAINT fk_tearigath_on_team_match FOREIGN KEY (match_id) REFERENCES matches (id);

DROP TABLE organizer_creation_request_approver_roles CASCADE;

DROP TABLE referee_creation_request_approver_roles CASCADE;

ALTER TABLE coach_creation_request_approver_roles
DROP
CONSTRAINT coach_creation_request_approver_roles_pkey;

ALTER TABLE referee_creation_requests
DROP
COLUMN category;

ALTER TABLE referee_creation_requests
DROP
COLUMN license_number;

ALTER TABLE referee_creation_requests
DROP
COLUMN license_series;

ALTER TABLE referees
DROP
COLUMN category;

ALTER TABLE athlete_creation_requests
DROP
COLUMN club_id;

ALTER TABLE athlete_creation_requests
DROP
COLUMN height;

ALTER TABLE athlete_creation_requests
DROP
COLUMN weight;

ALTER TABLE coach_creation_requests
DROP
COLUMN license_number;

ALTER TABLE coach_creation_requests
DROP
COLUMN license_series;

ALTER TABLE organizer_creation_requests
DROP
COLUMN trn_series;

DROP SEQUENCE clubs_id_seq CASCADE;

DROP SEQUENCE invitations_id_seq CASCADE;

DROP SEQUENCE request_info_id_seq CASCADE;

DROP SEQUENCE users_id_seq CASCADE;

ALTER TABLE coaches
ALTER
COLUMN license_number TYPE VARCHAR USING (license_number::VARCHAR);

ALTER TABLE referees
ALTER
COLUMN license_number TYPE VARCHAR USING (license_number::VARCHAR);

ALTER TABLE coaches
ALTER
COLUMN license_series TYPE VARCHAR USING (license_series::VARCHAR);

ALTER TABLE referees
ALTER
COLUMN license_series TYPE VARCHAR USING (license_series::VARCHAR);

ALTER TABLE organizers
ALTER
COLUMN trn_series TYPE VARCHAR USING (trn_series::VARCHAR);